### ISSUE TITLE
Implement fill_row in Display class

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_Blinka_Displayio#12]

**Comment by FoamyGuy** [comment]
I'm going to make an attempt to implement this over the upcoming weekend. 

While I was looking into a way to take screenshots for Circuit Python devices I realized we already have a library for that: https://github.com/adafruit/Adafruit_CircuitPython_BitmapSaver

I poked around it a little bit and I think if we have `fill_row` implemented and possibly a few other tweaks in the library it may be able to work on Blinka displayio objects.  Then we can have a common screenshot API that works for both, instead of relying on PIL to save an image like I have done now.

**Comment by makermelissa** [comment]
Sounds good. I've been doing most of the coding for this by looking are the circuitpython source code and translating it into the Python code except where it has functionality already built into Pillow. In this case, for fill row, you could probably make use of the pillow getpixel() function.

**Comment by makermelissa** [comment]
Fixed via #33.
