### ISSUE TITLE
Add I2C Display support

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_Blinka_Displayio#2]

**Comment by github-throwaway** [comment]
Is this still on the roadmap? :)

**Comment by makermelissa** [comment]
Yes

**Comment by ladyada** [comment]
hi we dont give ETA for code

PRs are always welcome! you can take a look at how we handle SPI and also at this PR https://github.com/adafruit/Adafruit_Blinka_Displayio/pull/41 see if you can get it working :)

**Comment by wolfmanjm** [comment]
I have implemented the I2CDisplay - https://github.com/adafruit/Adafruit_Blinka_Displayio/pull/41#issuecomment-804889522 however I am unable to fully test it with an SSD1306 due to monochrome not currently supported in BlinkaDisplayio.

If anyone can test it with an I2C color display I'd appreciate it :)
